## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file icecream.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_0p057 = RealNumber('0.057'); _sage_const_29 = Integer(29); _sage_const_10 = Integer(10); _sage_const_22 = Integer(22); _sage_const_0p17 = RealNumber('0.17'); _sage_const_18 = Integer(18); _sage_const_36 = Integer(36)## This file (icecream.sagetex.sage) was *autogenerated* from icecream.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('icecream', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
 sage.misc.preparser.load(sage.misc.preparser.base64.b64decode("c21vb3RoZXJzLnNweXg="),globals(),False)
 sage.misc.preparser.load(sage.misc.preparser.base64.b64decode("c21vb3RoZXJzLnNhZ2U="),globals(),False)
 patterns=ssv_to_list_of_lists("icecream.ssv")
 g1=show_smoother(-_sage_const_0p057 , _sage_const_0 , xmin = _sage_const_10 , xmax = _sage_const_36 )
 g2=show_smoother(_sage_const_0p17 , xmin = _sage_const_10 , xmax = _sage_const_36 )
except:
 _st_.goboom(_sage_const_18 )
_st_.blockend()
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=g1)
except:
 _st_.goboom(_sage_const_22 )
try:
 _st_.plot(_sage_const_1 , format='notprovided', _p_=g2)
except:
 _st_.goboom(_sage_const_29 )
_st_.endofdoc()
