## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file smoothers.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_260 = Integer(260); _sage_const_208 = Integer(208); _sage_const_8 = Integer(8); _sage_const_119 = Integer(119); _sage_const_47 = Integer(47); _sage_const_49 = Integer(49); _sage_const_193 = Integer(193); _sage_const_210 = Integer(210); _sage_const_332 = Integer(332); _sage_const_191 = Integer(191); _sage_const_330 = Integer(330); _sage_const_258 = Integer(258); _sage_const_271 = Integer(271); _sage_const_121 = Integer(121); _sage_const_93 = Integer(93); _sage_const_91 = Integer(91); _sage_const_269 = Integer(269); _sage_const_220 = Integer(220); _sage_const_222 = Integer(222)## This file (smoothers.sagetex.sage) was *autogenerated* from smoothers.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('smoothers', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
      p=load("boxfit")
   
except:
 _st_.goboom(_sage_const_47 )
_st_.blockend()
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_49 )
_st_.blockbegin()
try:
      p=load("smear")
   
except:
 _st_.goboom(_sage_const_91 )
_st_.blockend()
try:
 _st_.plot(_sage_const_1 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_93 )
_st_.blockbegin()
try:
      p=load("smoothfit")
   
except:
 _st_.goboom(_sage_const_119 )
_st_.blockend()
try:
 _st_.plot(_sage_const_2 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_121 )
_st_.blockbegin()
try:
      p=load("verysmoothfit")
   
except:
 _st_.goboom(_sage_const_191 )
_st_.blockend()
try:
 _st_.plot(_sage_const_3 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_193 )
_st_.blockbegin()
try:
      p=load("indometh0")
   
except:
 _st_.goboom(_sage_const_208 )
_st_.blockend()
try:
 _st_.plot(_sage_const_4 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_210 )
_st_.blockbegin()
try:
      p=load("indometh1")
   
except:
 _st_.goboom(_sage_const_220 )
_st_.blockend()
try:
 _st_.plot(_sage_const_5 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_222 )
_st_.blockbegin()
try:
      p=load("icecream0")
   
except:
 _st_.goboom(_sage_const_258 )
_st_.blockend()
try:
 _st_.plot(_sage_const_6 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_260 )
_st_.blockbegin()
try:
      p=load("icecream1")
   
except:
 _st_.goboom(_sage_const_269 )
_st_.blockend()
try:
 _st_.plot(_sage_const_7 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_271 )
_st_.blockbegin()
try:
      p=load("crossplot")
   
except:
 _st_.goboom(_sage_const_330 )
_st_.blockend()
try:
 _st_.plot(_sage_const_8 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_332 )
_st_.endofdoc()
