## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file wiggle100.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_49 = Integer(49); _sage_const_66 = Integer(66); _sage_const_64 = Integer(64); _sage_const_38 = Integer(38); _sage_const_23 = Integer(23); _sage_const_21 = Integer(21); _sage_const_51 = Integer(51); _sage_const_36 = Integer(36)## This file (wiggle100.sagetex.sage) was *autogenerated* from wiggle100.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('wiggle100', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
      p=load("wiggle100_order0")
   
except:
 _st_.goboom(_sage_const_21 )
_st_.blockend()
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_23 )
_st_.blockbegin()
try:
      p=load("wiggle100_order0_compare")
   
except:
 _st_.goboom(_sage_const_36 )
_st_.blockend()
try:
 _st_.plot(_sage_const_1 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_38 )
_st_.blockbegin()
try:
      p=load("wiggle100_order1")
   
except:
 _st_.goboom(_sage_const_49 )
_st_.blockend()
try:
 _st_.plot(_sage_const_2 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_51 )
_st_.blockbegin()
try:
      p=load("wiggle100_order1_compare")
   
except:
 _st_.goboom(_sage_const_64 )
_st_.blockend()
try:
 _st_.plot(_sage_const_3 , format='notprovided', _p_=p)
except:
 _st_.goboom(_sage_const_66 )
_st_.endofdoc()
